### ISSUE TITLE
Unneeded Requirements in the manifest.json file

### ISSUE THREAD

**Issue by Amit-Shan** [rkzofficial/ha-miraie-ac#11]
According to the Home Assistant developer documentation, the manifest file for custom integrations should only include requirements not required in Home Assistant Core. 

Link 1: https://developers.home-assistant.io/docs/creating_integration_manifest/#custom-integration-requirements
Link 2: https://github.com/home-assistant/core/blob/dev/requirements.txt

The aiohttp requirement is listed in the HA Core requirements and therefore does not need to be included. I believe this should also solve issues with the aiohttp version in HA being constantly upgraded and causing version mismatch errors with future updates.

Disclaimer: I am not a developer and as such, anything that I say is with the understanding of a regular consumer. I apologize if there are factors beyond my understanding in these suggestions.

PS: Could the other requirements also be made less strict? Instead of using a strict equality as a check, perhaps using a greater than or lesser than version check for the requirements?

**Comment by rkzofficial** [comment]
@Amit-Shan, you are right, Thanks for info will do necessary changes.

**Comment by Amit-Shan** [comment]
@rkzofficial It appears one of the changes broke the integration. The devices seem to be available in HA, but any commands to the devices result in an error stating that the client is not connected. I went into the manifest file and downgraded the aiomqtt package back to version 1.0.0. Rebooted HA and everything started working again. I did completely remove and re-add the integration and the same error started up until I downgraded the aiomqtt package again. So, I am pretty sure the error might be related to the aiomqtt package. Perhaps some breaking change.

**Comment by rkzofficial** [comment]
> @rkzofficial It appears one of the changes broke the integration. The devices seem to be available in HA, but any commands to the devices result in an error stating that the client is not connected. I went into the manifest file and downgraded the aiomqtt package back to version 1.0.0. Rebooted HA and everything started working again. I did completely remove and re-add the integration and the same error started up until I downgraded the aiomqtt package again. So, I am pretty sure the error might be related to the aiomqtt package. Perhaps some breaking change with the new versions.

I have fixed this issue now. There were some breaking changes in the latest version of aiomqtt library that's why it was causing the issues.

**Comment by Amit-Shan** [comment]
Sounds good. I shall update my integration.
