### ISSUE TITLE
Miraie AC python package fails installation (Conflicting dependencies)

### ISSUE THREAD

**Issue by Amit-Shan** [rkzofficial/ha-miraie-ac#13]
I updated the integration to the newest version, but it seems like the recent changes to the underlying python package created a few errors. It no longer works now. Screenshot of logs attached below.

![image](https://github.com/rkzofficial/ha-miraie-ac/assets/68187312/c8df93b2-24dc-43aa-b4ae-d94e8160783c)

Logs: "Unable to install package miraie-ac==1.0.0: ERROR: Cannot install miraie-ac==1.0.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts"

**Comment by Amit-Shan** [comment]
I first edited the manifest file and upgraded the "miraie-ac" package to "1.0.1", the latest version from your other repository. That did not work. The same error kept showing up. I then downgraded it to the last known working version, "0.2.16". Now, everything works fine. 

I hope this helps in troubleshooting.

**Comment by Amit-Shan** [comment]
Spoke too soon. The error about the client being offline has returned. I also needed to downgrade the aiomqtt package back to 1.0.0 for everything to work again.

Apologies. I should have checked the commit history before claiming that I fixed my issue. I would have realised I was wrong immediately.

**Comment by rkzofficial** [comment]
@Amit-Shan I am looking into the issue expect it to be fixed in few hours.

**Comment by Amit-Shan** [comment]
Sounds good! Thanks for everything!

**Comment by rkzofficial** [comment]
Fixed now! please update.

**Comment by Amit-Shan** [comment]
> Fixed now! please update.

Great! Thanks a lot for the continued support!
