### ISSUE TITLE
Can you please add icon to your custom repository in HA?

### ISSUE THREAD

**Issue by maxakash** [rkzofficial/ha-miraie-ac#15]
Hi
This repository doesn't have an icon. If you get time, please make a pull request to include your icon.
Here is the link : https://github.com/home-assistant/brands
Here is the icon link : https://shorturl.at/agDG6

Thanks

**Comment by deCodeIt** [comment]
I wonder if we can use that icon as it's a trademark of a brand which we aren't officially affiliated with.

**Comment by maxakash** [comment]
> I wonder if we can use that icon as it's a trademark of a brand which we aren't officially affiliated with.

I have seen many unofficial integrations using icons.
Also we are not using the icon in the integration, just submitting it to HA database.

**Comment by deCodeIt** [comment]
Created a PR here https://github.com/home-assistant/brands/pull/5731
