### ISSUE TITLE
Incompatible with the HACS 2.0 Update 

### ISSUE THREAD

**Issue by Amit-Shan** [rkzofficial/ha-miraie-ac#24]
HACS was recently updated to 2.0. I think the latest version of this integration is no longer compatible with the latest version of HACS. I keep getting an error when I try to update this integration. Screenshot attached below.
![image](https://github.com/user-attachments/assets/702dca50-c2f3-41fb-a9ac-e0df8a6c3570)

**Comment by deCodeIt** [comment]
Looks like we need a `hacs.json` file in the project root.
https://github.com/hacs/integration/blob/8e594101704b35ce70a5a88d13da2e2e10878d04/custom_components/hacs/repositories/base.py#L1402
