### ISSUE TITLE
Not able to setup . No Devices or Entities 

### ISSUE THREAD

**Issue by gaurishpathare** [rkzofficial/ha-miraie-ac#27]
![Screenshot_20240828_002709_Home Assistant](https://github.com/user-attachments/assets/fd6660c7-3a40-4b4d-b81d-d4c9d41a7d61)

Followed the steps as mentioned but getting an error when I open the miraie integration as - No Devices or Entities. Failed to setup.

**Comment by gaurishpathare** [comment]
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 00:18:35 (1 occurrences)
Last logged: 00:18:35

Error setting up entry MirAIe for miraie
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/miraie/__init__.py", line 22, in async_setup_entry
    await hub.init(entry.data["username"], entry.data["password"], broker)
  File "/usr/local/lib/python3.12/site-packages/miraie_ac/hub.py", line 37, in init
    await self.get_all_device_status()
  File "/usr/local/lib/python3.12/site-packages/miraie_ac/hub.py", line 217, in get_all_device_status
    converti_mode=ConvertiMode(status.get("cnv", 0)),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 1 is not a valid ConvertiMode

**Comment by deCodeIt** [comment]
Request you to enable logs for our integration ( Check out our readme on how to do it )

Can you share the Panasonic product spec page for your ac? Similar to https://www.panasonic.com/in/consumer/air-conditioners/split-ac/cs-cu-hu12zkyf.specs.html

I'm interested in the ac model as I haven't seen a convert mode value of 1 in the past.

Secondly, if your ac does support convert modes, can you set the mode to 0/OFF or maybe use ECO or POWER mode before initialising MirAIe in Home Assistant to see if it gets added or not ( Do share logs for each case here ).

**Comment by Amit-Shan** [comment]
I have the same issue. The integration no longer works after the latest Home Assistant update. 

Model: https://www.panasonic.com/in/consumer/air-conditioners/split-ac/cs-cu-nu12xkywa.html

Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 10:29:33 (1 occurrences)
Last logged: 10:29:33

> Logger: homeassistant.config_entries
> Source: config_entries.py:594
> First occurred: 10:29:33 (1 occurrences)
> Last logged: 10:29:33
> 
> Error setting up entry MirAIe for miraie
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/miraie/__init__.py", line 22, in async_setup_entry
>     await hub.init(entry.data["username"], entry.data["password"], broker)
>   File "/usr/local/lib/python3.12/site-packages/miraie_ac/hub.py", line 37, in init
>     await self.get_all_device_status()
>   File "/usr/local/lib/python3.12/site-packages/miraie_ac/hub.py", line 217, in get_all_device_status
>     converti_mode=ConvertiMode(status.get("cnv", 0)),
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
>     return cls.__new__(cls, value)
>            ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
>     raise ve_exc
> ValueError: 1 is not a valid ConvertiMode

**Comment by deCodeIt** [comment]
> I have the same issue. The integration no longer works after the latest Home Assistant update. The model does not support convert modes as far as I know. I am also unable to change any of the modes before initialization.
> 
> Model: https://www.panasonic.com/in/consumer/air-conditioners/split-ac/cs-cu-nu12xkywa.html
> 
> Logger: homeassistant.config_entries Source: config_entries.py:594 First occurred: 10:29:33 (1 occurrences) Last logged: 10:29:33
> 
> > Logger: homeassistant.config_entries
> > Source: config_entries.py:594
> > First occurred: 10:29:33 (1 occurrences)
> > Last logged: 10:29:33
> > Error setting up entry MirAIe for miraie
> > Traceback (most recent call last):
> > File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
> > result = await component.async_setup_entry(hass, self)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "/config/custom_components/miraie/**init**.py", line 22, in async_setup_entry
> > await hub.init(entry.data["username"], entry.data["password"], broker)
> > File "/usr/local/lib/python3.12/site-packages/miraie_ac/hub.py", line 37, in init
> > await self.get_all_device_status()
> > File "/usr/local/lib/python3.12/site-packages/miraie_ac/hub.py", line 217, in get_all_device_status
> > converti_mode=ConvertiMode(status.get("cnv", 0)),
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "/usr/local/lib/python3.12/enum.py", line 757, in **call**
> > return cls.**new**(cls, value)
> > ^^^^^^^^^^^^^^^^^^^^^^^
> > File "/usr/local/lib/python3.12/enum.py", line 1171, in **new**
> > raise ve_exc
> > ValueError: 1 is not a valid ConvertiMode

Hi @Amit-Shan 
Thank you for sharing the model page.
From the specs I see it doesn't support convertible modes and maybe that's the reason the convert value was coming out to be 1 ( not-supported ). We need to update our codebase to support non-converti ac as well. I'll be working on a fix for this.
