### ISSUE TITLE
After logging in, no devices are added

### ISSUE THREAD

**Issue by maxakash** [rkzofficial/ha-miraie-ac#8]
Hi @rkzofficial  , after login, here is the error I got
```
2024-02-24 22:42:18.259 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry MirAIe for miraie
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/miraie/__init__.py", line 23, in async_setup_entry
await hub.init(entry.data["username"], entry.data["password"], broker)
File "/usr/local/lib/python3.12/site-packages/miraie_ac/hub.py", line 37, in init
await self.get_all_device_status()
File "/usr/local/lib/python3.12/site-packages/miraie_ac/hub.py", line 202, in get_all_device_status
temperature=toFloat(status["actmp"]),
~~~~~~^^^^^^^^^
KeyError: 'actmp'
2024-02-24 22:42:29.963 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry MirAIe for miraie
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/miraie/__init__.py", line 23, in async_setup_entry
await hub.init(entry.data["username"], entry.data["password"], broker)
File "/usr/local/lib/python3.12/site-packages/miraie_ac/hub.py", line 37, in init
await self.get_all_device_status()
File "/usr/local/lib/python3.12/site-packages/miraie_ac/hub.py", line 202, in get_all_device_status
temperature=toFloat(status["actmp"]),
~~~~~~^^^^^^^^^
KeyError: 'actmp'
```

**Comment by rkzofficial** [comment]
Hi @maxakash ,

Thanks for raising the issue, could you please tell me more about the devices you are trying to use?

Model number, features etc. of the device.

**Comment by maxakash** [comment]
> Hi @maxakash ,
> 
> Thanks for raising the issue, could you please tell me more about the devices you are trying to use?
> 
> Model number, features etc. of the device.

I have 7 Panasonic ACs and on Smart Refrigertor. They all work with MirAie app and miraie node red plugin.

**Comment by rkzofficial** [comment]
> > Hi @maxakash ,
> > 
> > Thanks for raising the issue, could you please tell me more about the devices you are trying to use?
> > 
> > Model number, features etc. of the device.
> 
> I have 7 Panasonic ACs and 1 Smart Refrigerator. They all work with MirAie app and miraie node red plugin.

Understood, I know now why this plugin is failing, when I created this plugin I only consider the Panasonic AC not other devices, as of now this plugin is only compatible with Panasonic ACs. Currently this plugin is treating the smart refrigerator as AC and thus failing in the process.

To mitigate this issue, I need to write a filter to only import Panasonic AC not other devices.

I will probably do this in couple of days.

**Comment by maxakash** [comment]
> > > Hi @maxakash ,
> > > Thanks for raising the issue, could you please tell me more about the devices you are trying to use?
> > > Model number, features etc. of the device.
> > 
> > 
> > I have 7 Panasonic ACs and 1 Smart Refrigerator. They all work with MirAie app and miraie node red plugin.
> 
> Understood, I know now why this plugin is failing, when I created this plugin I only consider the Panasonic AC not other devices, as of now this plugin is only compatible with Panasonic ACs. Currently this plugin is treating the smart refrigerator as AC and thus failing in the process.
> 
> To mitigate this issue, I need to write a filter to only import Panasonic AC not other devices.
> 
> I will probably do this in couple of days.

Yes here are the model numbers CS-CU-TU18ZKY-1,  CS-CU-ZU24ZKYF

**Comment by maxakash** [comment]
After removing the refrigerator, I am able to add the ACs.

**Comment by maxakash** [comment]
Hi @rkzofficial Did you get time to work on it?

Thank

**Comment by rkzofficial** [comment]
@maxakash I just moved to my hometown, now I have some free time to work on this.

**Comment by maxakash** [comment]
@rkzofficial I have updated but still refrigerator is not supported.
Please look into it.

**Comment by rkzofficial** [comment]
@maxakash I made some changes to only allow Panasonic ACs devices to be integrated, I don't have plan to support refrigerators for now maybe in near future. I am closing this issue now. For supporting the refrigerator, please open new feature request.
